polcode_chess_homepage:
    pattern:  /
    defaults: { _controller: PolcodeChessBundle:Default:index }

new_game:
    pattern: /create
    defaults: { _controller: PolcodeChessBundle:Game:create }
    
join_game:
    pattern: /join/{game_id}
    defaults: { _controller: PolcodeChessBundle:Game:join }
    
display:
    pattern: /display/{game_id}
    defaults: { _controller: PolcodeChessBundle:Game:display }