services:
    GameMaster:
        class: Polcode\ChessBundle\Model\GameMaster
        arguments: [@doctrine.orm.entity_manager, @gameutilities]

    GameUtilities:
        class: Polcode\ChessBundle\Model\GameUtilities