parameters:
#    polcode_chess.example.class: Polcode\ChessBundle\Example

services:
    GameMaster:
        class: Polcode\ChessBundle\Model\GameMaster
        arguments: [@doctrine.orm.entity_manager]
